### ISSUE TITLE
Update documentation for dbproxy

### ISSUE THREAD

**Issue by drewwells** [infobloxopen/db-controller#325]
update dbproxy to include new labels:

```
      - key: "persistance.atlas.infoblox.com/claim"
        operator: "Exists"
      - key: "persistance.atlas.infoblox.com/dbproxy"
        operator: "In"
        values:
          - "enabled"
        # Important to prevent multiple db-controllers from stepping on each other
      - key: "persistance.atlas.infoblox.com/class"
        operator: "In"
        values:
          - {{ .Values.dbController.class | quote }}
```
